name: CA
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Get deployment URL
        id: get-deployment-url
        run: |
          DEPLOYMENT_URL=$(railway variables get RAILWAY_STATIC_URL)
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          echo "::set-output name=deployment_url::$DEPLOYMENT_URL"

      - name: Send Slack notification
        run: |
          MESSAGE="Your application has been deployed! :tada: <${{ env.DEPLOYMENT_URL }}|Click here> to visit the site."
          PAYLOAD="{\"text\": \"$MESSAGE\"}"
          curl -s -X POST -H 'Content-type: application/json' --data "$PAYLOAD" ${{ secrets.SLACK_WEBHOOK_URL }}
