name: CA
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Railway
      run: |
        curl --request POST \
          --url https://api.railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/deploy \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}'