name: CA
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Railway CLI
      run: |
        curl -L https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | bash

    - name: Set Railway API token
      run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV

    - name: Deploy to Railway
      run: railway up